### ISSUE TITLE
Exception on request and no response

### ISSUE THREAD

**Issue by imduffy15** [travelaudience/nexus-proxy#4]
Hi All,

I'm running with the following `values.yaml` using the latest nexus helm chart:

```
nexusProxy:
  env:
    nexusDockerHost: docker.portdynamics.com
    nexusHttpHost: nexus.portdynamics.com

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
#    kubernetes.io/tls-acme: true
  tls: false

persistence:
  storageClass: standard
  storageSize: 1024Gi
```

On attempting to reach the proxy it throws an exception:

```
2018-05-11 14:26:36,180 [INFO ] [vert.x-eventloop-thread-0] [com.travelaudience.nexus.proxy.BaseNexusProxyVerticle] Listening at 0.0.0.0:8080.
2018-05-11 14:43:04,471 [ERROR] [vert.x-eventloop-thread-0] [io.vertx.ext.web.impl.RoutingContextImplBase] Unexpected exception in route
java.lang.NullPointerException: null
	at com.travelaudience.nexus.proxy.BaseNexusProxyVerticle.lambda$start$5(BaseNexusProxyVerticle.java:129)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:118)
	at io.vertx.ext.web.handler.impl.VirtualHostHandlerImpl.handle(VirtualHostHandlerImpl.java:54)
	at io.vertx.ext.web.handler.impl.VirtualHostHandlerImpl.handle(VirtualHostHandlerImpl.java:27)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:118)
	at io.vertx.ext.web.handler.impl.VirtualHostHandlerImpl.handle(VirtualHostHandlerImpl.java:54)
	at io.vertx.ext.web.handler.impl.VirtualHostHandlerImpl.handle(VirtualHostHandlerImpl.java:27)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:118)
	at io.vertx.ext.web.handler.impl.VirtualHostHandlerImpl.handle(VirtualHostHandlerImpl.java:54)
	at io.vertx.ext.web.handler.impl.VirtualHostHandlerImpl.handle(VirtualHostHandlerImpl.java:27)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:118)
	at com.travelaudience.nexus.proxy.BaseNexusProxyVerticle.lambda$start$0(BaseNexusProxyVerticle.java:80)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:118)
	at io.vertx.ext.web.impl.RouterImpl.accept(RouterImpl.java:79)
	at io.vertx.core.http.impl.ServerConnection.handleRequest(ServerConnection.java:285)
	at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:429)
	at io.vertx.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:131)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.lambda$createConnAndHandle$1(HttpServerImpl.java:770)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:335)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:193)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.createConnAndHandle(HttpServerImpl.java:764)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:628)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:580)
	at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:76)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:122)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:49)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:27)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
```

Any ideas?

**Comment by pires** [comment]
Please, provide more details on how to reproduce this. Where exactly did this request come from?

The only way I could reproduce this was to access Nexus from within the same Kubernetes cluster, and through a Service, not the external Ingress.

**Comment by pires** [comment]
Meanwhile, I have provided a fix for the NPE. See https://github.com/travelaudience/nexus-proxy/commit/f4c61ac006dca76bc06cd3a667075b82405ba2ad. It has been released as v2.2.0.

**Comment by jeff-knurek** [comment]
@imduffy15 can you apply `--set nexusProxy.imageTag=2.2.0` to your helm deploy and see if the error message provides any more insight into the issue?

**Comment by pires** [comment]
Great! 🎉

**Comment by leoamigud** [comment]
I am still getting this error on GCP, please suggest?

**Comment by leoamigud** [comment]
Please nevermind, that was a domain name typo!

**Comment by matthewrj** [comment]
I encountered this error. Using imageTag=2.2.0 fixed the problem for me.
